From nginx:1.21.3-alpine
COPY ./default.conf              /etc/nginx/conf.d/default.conf
COPY ./ssl-dhparams.pem          /etc/data/ssl-dhparams.pem
COPY ./options-ssl-nginx.conf    /etc/data/options-ssl-nginx.conf