import { Express } from "express";
import { currentUserRouter } from "../routes/lotto360/admin/auth/current.user";
import { signinRouter } from "../routes/lotto360/admin/auth/signin";
import { signoutRouter } from "../routes/lotto360/admin/auth/signout";
import { getRemainingBnbRouter } from "../routes/lotto360/admin/helpers/calculate.remain.bnb";
import { getBalanceStatsRouter } from "../routes/lotto360/admin/helpers/get.balance.stats";
import { getSettingsRouter } from "../routes/lotto360/admin/helpers/get.settings";
import { getWithdrawsRouter } from "../routes/lotto360/admin/helpers/get.withdraws";
import { setMaxTicketsPerBuyRouter } from "../routes/lotto360/admin/helpers/set.max.tickets.per.buy";
import { transferOwnerRouter } from "../routes/lotto360/admin/helpers/transfer.owner";
import { withdrawRouter } from "../routes/lotto360/admin/helpers/withdraw";
import { getPaymentsRouter } from "../routes/lotto360/admin/payments/get.payments";
import { getUserPaymentsRouter } from "../routes/lotto360/admin/payments/get.user.payment";
import { createRoundRouter } from "../routes/lotto360/admin/round/add.round";
import { closeRoundRouter } from "../routes/lotto360/admin/round/close.round";
import { drawRoundRouter } from "../routes/lotto360/admin/round/draw.round";
import { fetchRoundRouter } from "../routes/lotto360/admin/round/fetch.round";
import { getAllRoundsRouter } from "../routes/lotto360/admin/round/get.all";
import { getCurrentRoundRouter } from "../routes/lotto360/admin/round/get.current";
import { getRoundByIdAdminRouter } from "../routes/lotto360/admin/round/get.round.by.id";
import { getRoundByIdAdminFromDbRouter } from "../routes/lotto360/admin/round/get.round.by.id.db";
import { updateCurrentRoundRouter } from "../routes/lotto360/admin/round/update";
import { getAllTicketsRouter } from "../routes/lotto360/admin/ticket/get.all.tickets";
import { checkForWinRouter } from "../routes/lotto360/users/round/check.for.win";
import { getRoundByIdForUserRouter } from "../routes/lotto360/users/round/get.by.id";
import { checkUserHistoryRouter } from "../routes/lotto360/users/round/get.user.history";

export const registerLotto360Routes = (app: Express) => {
    app.use(getRoundByIdAdminFromDbRouter);
    app.use(getRoundByIdForUserRouter);
    app.use(setMaxTicketsPerBuyRouter);
    app.use(updateCurrentRoundRouter);
    app.use(getRoundByIdAdminRouter);
    app.use(checkUserHistoryRouter);
    app.use(getCurrentRoundRouter);
    app.use(getRemainingBnbRouter);
    app.use(getUserPaymentsRouter);
    app.use(getBalanceStatsRouter);
    app.use(transferOwnerRouter);
    app.use(getAllTicketsRouter);
    app.use(getAllRoundsRouter);
    app.use(getWithdrawsRouter);
    app.use(getSettingsRouter);
    app.use(createRoundRouter);
    app.use(checkForWinRouter);
    app.use(currentUserRouter);
    app.use(getPaymentsRouter);
    app.use(fetchRoundRouter);
    app.use(closeRoundRouter);
    app.use(drawRoundRouter);
    app.use(withdrawRouter);
    app.use(signoutRouter);
    app.use(signinRouter);
};
